export const heroesNicknameMap = {
  Alarak: ["alarak", "阿拉纳克", "高坚果"],
  Abathur: ["abathur", "阿巴瑟"],
  AnubArak: ["anubarak", "阿努巴拉克", "小强"],
  Arthas: ["arthas", "阿尔萨斯"],
  Auriel: ["auriel", "奥莉尔"],
  Azmodan: ["azmodan", "阿兹莫丹"],
  Butcher: ["butcher", "屠夫"],
  Brightwing: ["brightwing", "光明之翼", "精灵龙"],
  Cassia: ["cassia", "卡西娅"],
  Chen: ["chen", "陈", "熊猫"],
  ChoGall: ["chogall", "古加尔"],
  Chromie: ["chromie", "克罗米"],
  Dehaka: ["dehaka", "德哈卡"],
  DVa: ["dva", "D.Va"],
  Diablo: ["diablo", "迪亚波罗", "大菠萝"],
  Deathwing: ["deathwing", "死亡之翼", "大表哥"],
  ETC: ["etc", "精英牛头人酋长", "牛头"],
  Genji: ["genji", "源氏"],
  Garrosh: ["garrosh", "加尔鲁什", "小吼"],
  Greymane: ["greymane", "格雷曼恩"],
  Guldan: ["guldan", "古尔丹"],
  Illidan: ["illidan", "伊利丹", "丹哥"],
  Johanna: ["johanna", "乔汉娜"],
  Jaina: ["jaina", "吉安娜"],
  Kerrigan: ["kerrigan", "凯瑞甘"],
  KaelThas: ["kaelthas", "凯子", "凯尔萨斯"],
  Kharazim: ["kharazim", "卡拉辛姆", "武僧"],
  Lili: ["lili", "丽丽"],
  Liming: ["liming", "李敏"],
  Lunara: ["lunara", "露娜拉", "小鹿"],
  Lucio: ["lucio", "卢西奥", "dj"],
  Leoric: ["leoric", "李奥瑞克", "骷髅王"],
  Malthael: ["malthael", "马萨伊尔", "小马"],
  Malfurion: ["malfurion", "玛法里奥", "玛法"],
  Muradin: ["muradin", "穆拉丁"],
  Murky: ["murky", "奔波儿灞", "鱼人"],
  Morales: ["morales", "医生", "莫拉莉斯中尉"],
  Medivh: ["medivh", "麦迪文"],
  Naziba: ["naziba", "纳兹波", "巫医"],
  Nova: ["nova", "诺娃"],
  Qhira: ["qhira", "琪拉"],
  Raynor: ["raynor", "雷诺"],
  Rehgar: ["rehgar", "雷加尔", "老狗"],
  Rexxar: ["rexxar", "雷克萨"],
  SgHammer: ["sghammer", "重锤军士", "坦克"],
  Sonya: ["sonya", "桑娅"],
  Stitches: ["stitches", "缝合怪"],
  Sylvanas: ["sylvanas", "希尔瓦娜斯"],
  Stukov: ["stukov", "斯托科夫"],
  Tracer: ["tracer", "猎空"],
  Tassadar: ["tassadar", "塔萨达尔"],
  Thrall: ["thrall", "萨尔"],
  Tychus: ["tychus", "泰凯斯"],
  Gazlowe: ["gazlowe", "加兹鲁维"],
  Tyrael: ["tyrael", "泰瑞尔"],
  Tyrande: ["tyrande", "泰兰德"],
  Uther: ["uther", "乌瑟尔"],
  Valla: ["valla", "维拉"],
  Valeera: ["valeera", "瓦莉拉"],
  Xul: ["xul", "祖尔"],
  Zarya: ["zarya", "查莉娅", "毛妹"],
  Zagara: ["zagara", "扎加拉"],
  Zeratul: ["zeratul", "泽拉图"],
  Zuljin: ["zul'jin", "zuljin", "祖尔金"],
};
